# elastic-backend/docker-compose.yml
version: '3.8'

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch1
    environment:
      - node.name=es1
      - cluster.name=cv-transcriptions-cluster
      - discovery.seed_hosts=elasticsearch2 # Point to the other node
      - cluster.initial_master_nodes=es1,es2 # Define initial master nodes [cite: 34]
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false # Disable security for simplicity in test env
      - xpack.security.http.ssl.enabled=false # Disable SSL for simplicity
      - xpack.security.transport.ssl.enabled=false # Disable SSL for simplicity
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200" # URL: http://localhost:9200 [cite: 34]
    networks:
      - es_net

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch2
    environment:
      - node.name=es2
      - cluster.name=cv-transcriptions-cluster
      - discovery.seed_hosts=elasticsearch1 # Point to the other node
      - cluster.initial_master_nodes=es1,es2 # Define initial master nodes [cite: 34]
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false # Disable security for simplicity in test env
      - xpack.security.http.ssl.enabled=false # Disable SSL for simplicity
      - xpack.security.transport.ssl.enabled=false # Disable SSL for simplicity
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - es_net

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  es_net:
    driver: bridge